#List of actions:
uint8 OFF=0
uint8 ON=1
uint8 PATTERN=2
uint8 OFF_ALL=3

#Action: one of above list:
int32 action

#Name of the UI:
string name

#(action==PATTERN only) Time to start the pattern:
time start
#(action==PATTERN only) Sequence of on/off pattern:
bool[] on_off_traj
#(action==PATTERN only) Sequence of duration pattern corresponding to on_off_traj:
#  (NOTE: At the end of the pattern, the state is set to on_off_traj[-1])
float64[] dt_traj
#(action==PATTERN only) Number of repeating the [on_off_traj,dt_traj] pattern.
int32 n_repeat

---
bool res
